update workflows

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -22,8 +22,19 @@ jobs:
 
       - name: Check Secrets
         run: |
+          if [ -z "${{ secrets.MODRINTH_TOKEN }}" ]; then
+            echo "MODRINTH_TOKEN is not set"
+            exit 1
+          fi
           if [ -z "${{ secrets.CURSEFORGE_TOKEN }}" ]; then
             echo "CURSEFORGE_TOKEN is not set"
+            exit 1
+          fi
+
+      - name: Validate Modrinth Token
+        run: |
+          if [ -n "$(curl -s -H "Authorization: ${{ secrets.MODRINTH_TOKEN }}" https://api.modrinth.com/v2/user | grep "unauthorized")" ]; then
+            echo "Modrinth Token is invalid!"
             exit 1
           fi
 
@@ -45,7 +56,7 @@ jobs:
       - name: Validate Gradle wrapper
         uses: gradle/wrapper-validation-action@v1
 
-      - name: Assemble the JARs
+      - name: Assemble the jar
         run: ./gradlew assemble
 
       - name: Collect version information
@@ -56,10 +67,10 @@ jobs:
             echo $1="$2" >> $GITHUB_ENV
             declare -g $1="$2"
           }
-          set_var JAR_FILE $(eval echo build/libs/${{ env.MOD_ID }}-*-*-*.jar)
-          set_var MINECRAFT_VERSION $(echo ${JAR_FILE%.*} | cut -d- -f3)
-          set_var MOD_VERSION $(echo ${JAR_FILE%.*} | cut -d- -f4)
-          set_var RELEASE_TYPE "$(echo ${GITHUB_REF##*/} | cut -d- -f3)"
+          set_var JAR_FILE $(eval echo build/libs/${{ env.MOD_ID }}-*-*.jar)
+          set_var MINECRAFT_VERSION $(echo ${JAR_FILE%.*} | cut -d- -f2)
+          set_var MOD_VERSION $(echo ${JAR_FILE%.*} | cut -d- -f3)
+          set_var RELEASE_TYPE "$(echo ${GITHUB_REF##*/} | cut -d- -f4)"
           set_var RELEASE_TYPE "$([[ -z $RELEASE_TYPE ]] && echo release || echo $RELEASE_TYPE)"
 
       - name: Install changelog parser
@@ -68,24 +79,28 @@ jobs:
       - name: Parse changelog
         run: parse-changelog CHANGELOG.md ${{ env.MOD_VERSION }} > changes.md
 
-      - name: Release Fabric Mod to CF
+      - name: Release
         uses: Kir-Antipov/mc-publish@v3.2
         with:
           curseforge-id: 622888
           curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
+          modrinth-id: 5A34Stj8
+          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
+          github-token: ${{ secrets.GITHUB_TOKEN }}
 
-          files: build/libs/${{ env.MOD_ID }}-fabric-${{ env.MINECRAFT_VERSION }}-${{ env.MOD_VERSION }}.jar
-          name: ${{ env.MOD_NAME }}-${{ env.MOD_VERSION }}-${{ env.MINECRAFT_VERSION }} [Fabric]
-          version: ${{ env.MINECRAFT_VERSION }}-${{ env.MOD_VERSION }}+fabric
-          version-type: ${{ env.RELEASE_TYPE }}
-          changelog-file: changes.md
+          files: ${{ env.JAR_FILE }}
+          name: ${{ env.MOD_NAME }}-Fabric-${{ env.MINECRAFT_VERSION }}-${{ env.MOD_VERSION }}
+          github-name: v${{ env.MINECRAFT_VERSION }}-${{ env.MOD_VERSION }}-Fabric
 
           loaders: fabric
           game-versions: ${{ env.MINECRAFT_VERSION }}
+          version: ${{ env.MINECRAFT_VERSION }}-${{ env.MOD_VERSION }}+fabric
+          version-type: ${{ env.RELEASE_TYPE }}
           version-resolver: exact
           java: ${{ env.JAVA_VERSION }}
 
-          curseforge-dependencies: |
+          changelog-file: changes.md
+          dependencies: |
             create-fabric | depends | *
             kubejs | depends | *
 
